FROM node:latest as builder

COPY . /usr/src/beerpong-fe
WORKDIR /usr/src/beerpong-fe
RUN ls
RUN npm install
RUN npm install -g @angular/cli

EXPOSE 4200

CMD ng serve --host 0.0.0.0 --disable-host-check